# ----------------------------------------------------------------------------------
# Filename:     variables_default.yml
# Description:  FlexGet & FileBot account credentials and basic path
#               variables for config.yml. Edit with caution.
# ----------------------------------------------------------------------------------

# ### Warning ####
# When editing this file do so with strict attention to the following rules.
#   1.  Indentation level: always use (multiples of) two spaces and never use the tab key!
#   2.  Value indentation: always use one space only after the descriptor!
#         Example:
#             account: ahuacate
#   3.  If a text value contains any of these characters {}[]%: it must
#       be quoted with '' (apostrophes).
#   4.  If you want to pass a number as a text (i.e. the series 24), the value
#       must be quoted with '' (apostrophes).
#   5. Only edit your account details (username and password) if you do not know
#      what you are doing.
#   6. Change the value NOT the variable name!!!!


#---- Deluge Torrent Downloader

# To find your deluge user and password type "cat /home/media/.config/deluge/auth" in your LXC hosting Deluge SW
# Do not edit if you using our Ahuacate Deluge CT installation.
# If FlexGet connectivity with Deluge fails change <deluge.host> to a IP address and
# set dhcp reservation for your deluge host (i.e dhcp reserved or static IP).
deluge:
  username: appconnect
  password: ahuacate
  host: deluge.local # IP address also works here
  port: 58846


#---- Trakt Account

# Add your account details here. If you haven't done so log into your Trakt account
# and create the following two Trakt lists: (list names must be identical, all lowercase)
#   'documentary-series' and 'documentary-movie'
trakt:
  account: ahuacate
  username: ahuacate
  documentary_series_list: documentary-series
  documentary_movie_list: documentary-movie


#---- Language

# Set your preferred language
# Must use ISO 639-1 language codes. (i.e en,de,it,fa)
# See here: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
subtitle:
  lang: en


#---- RSS torrent accounts

# MVGroup Account
# Your MVGroup user account rss url is available here: https://forums.mvgroup.org/rss.php?listfeeds=1
# Example: (note the lowercase 'url' :)
#      url: https://<username>:<password>@forums.mvgroup.org/rss.php?torrentsonly=1
mvgroup:
  url: https://twoelles:4d17d02aa482dd386ac220a1e98e1e8d@forums.mvgroup.org/rss.php?torrentsonly=1


#---- FileBot naming convention

# Each Media server application has a preferred file naming convention.
# You have the option of 'plex.id', 'emby.id' or 'jellyfin.id'.
# Set your media server type exactly as shown. Default is 'jellyfin.id'.
# Examples:
#      Jellyfin: 'jellyfin.id'
#      Emby:     'emby.id'
#      Plex:     'plex.id'
mediaserver:
  type: jellyfin.id


#-----------------------------------------------------------------------------------
# NO NOT EDIT HERE DOWN
# Only edit here down if you know what you are doing.

#---- Prune options

# Prune is a action to delete video content after a set number of days.
# Prune is applied to '.../video/documentary/{series,movies}' and
# '/mnt/downloads/unsorted' only.
# Example:
#      'documentary_series_days: 14' will delete all content aged 14 days or more.
# Set '0' to disable.
prune:
  # Documentary series (days)
  age_documentary_series: 14
  # Documentary movies (days)
  age_documentary_movies: 21
  # Unsorted media (days) (i.e /mnt/downloads/unsorted)
  age_unsorted: 7


#---- FileBot options

# Find age limit
# The FileBot script scans the "src" directories for newly added content, but it
# applies a file age limit in hours to the media files it processes. This ensures
# that only recent files are processed, instead of processing all media files in
# the "src" directory. The script operates in conjunction with FlexGet and is
# triggered by a system.d timer, which is typically set to run every 6 hours.
# It's crucial to ensure that the FileBot age limit is set longer than the
# system.d timer setting. We recommend setting an age limit of 24 hours,where 
# units are measured in hours.
filebot:
  age_src: 24


#---- Storage base Mount Points

# Storage are the base mount points. They are paths for downloads, video, music folders
# but not video category (i.e series, pron, movies). Category paths are set 'paths'
storage:
  # Base download dir.
  downloads: /mnt/downloads
  # This is where Deluge completed downloads are moved to.
  downloads_torrent: /mnt/downloads/torrent/complete/manual
  # This is where NZBGet completed downloads are moved to.
  downloads_usenet: /mnt/downloads/usenet/complete/manual
  # Base destination video share (dst).
  video: /mnt/video
  # Base destination music share (dst).
  music: /mnt


#---- Paths

# Paths to media src and dst dirs. There must be a matching pair of
# src and dst paths. Note the naming convention. Example:
#     1)   "path.series_dst: /mnt/video/series"
#     2)   "path.series_src: /mnt/downloads/torrent/complete/manual/series"
path:
  # Destination dirs (dst)
  series_dst: series
  movies_dst: movies
  anime_dst: anime
  music_dst: music
  musicvideo_dst: musicvideo
  documentary_series_dst: documentary/series
  documentary_movies_dst: documentary/movies
  documentary_unsorted_dst: null_entry
  # Downloaded source dirs (src - complete only) 
  series_src: series
  movies_src: movies
  anime_src: anime
  music_src: music
  musicvideo_src: musicvideo
  documentary_series_src: documentary/series
  documentary_movies_src: documentary/movies
  documentary_unsorted_src: documentary/unsorted

  # Unsorted dir (dst)
  # This is the dir where FileBot copies unknown/unmatched files to.
  # Its should always be /mnt/download/unsorted.
  # The user can manually process these with GUI version of FileBot.
  unsorted: unsorted


#---- FlexGet manipulate variables

# MVGroup Regex variables
mvg:
  # Capture all
  capture_all: '(.*?)'
  # Capture s00e00
  capture_s00e00: '(?:(s\d+e\d+))'
  # Include lookahead s00e00 (insert at start of regex)
  include_s00e00: '(?=\.(s\d+e\d+)\.)'
  # Exclude lookahead s00e00 (insert at start of regex)
  exclude_s00e00: '(?!\.s\d+e\d+\.)'
  # Capture file extension
  capture_file_ext: '([^.]+$)'
  # Capture optional info
  # capture_opt_info: '(.*)'
  # Capture year (years 1900-2099 only)
  capture_year: '(?:(20\d{2}|19\d{2}))'
  # Include year (insert at start of regex)
  include_year: '(?=\.(20\d{2}|19\d{2})\.)'
  # Exclude year (insert at start of regex)
  exclude_year: '(?!(?:\.20\d{2}\.|\.19\d{2}\.))'
  # Video metadata keywords
  # Lookahead for first metadata keyword in a string (hdtv,webdl,720p,1080p etc)
  quality_metadata: '(?=\.(\d{3,4}[pi]|hdtv|web[-_]?dl|x265|h265|x264|h264|hdtv\.pdtv\.dvd|blu[-_]?ray))'
  # Capture broadcaster name only
  # Lookahead for first word only that identifies a broadcaster (i.e bbc,nhk)
  capture_broadcaster_name: '(?:(bbc(?!\.documentaries)|ch[0-9]?|itv(?!\.documentaries)|nhk(?!\.documentaries|\.world\.documentaries)|s4c|sbs|ng|uktv|sky|bskyb|dw(?!\.documentaries)|canal|\(cit\)|%28CIT%29|central\.independent\.television|arte|pbs(?!\.documentaries|\.specials)|cnn|national\.geographic|discovery|pmt|ft|history\.channel|ht|curiosity\.stream|netflix|abc))'
  # Exclude broadcaster name only
  exclude_broadcaster_name: '(?!(?:bbc\.documentaries?|ch[0-9]?|itv\.documentaries?|nhk\.documentaries?|nhk\.world|nhk\.world\.documentaries|s4c|sbs|ng|uktv|sky|bskyb|dw|canal|\(cit\)|%28CIT%29|central\.independent\.television|arte|pbs\.documentaries?|pbs.specials|cnn|national\.geographic|discovery|pmt|ft|history\.channel|ht|curiosity\.stream|netflix|abc).*)'

  # Sort for Deluge labels (dst). Used by task 'torrent_rss_documentary'.
  # Do not edit.
  # Include s00e00 or Broadcaster and no Year
  sort_series: '(?:(\[\bseries\b.*\]))'
  # Include year, no s00e00
  sort_movie: '(?:(\[\bmovie\b.*\]))'
  # Exclude broadcaster, year, s00e00
  sort_unsorted: '(?:(\[\bunsorted\b.*\]))'
#-----------------------------------------------------------------------------------